import { useCallback } from "react";
import { Activity, CalendarDays, ClipboardList, House, MessageCircle, Pill, Wind } from "lucide-react";
import { Link } from "react-router-dom";
import { PortalPageHeader } from "@/components/patient-portal/PortalPageHeader";
import { PortalEmptyState, PortalErrorState, PortalIncompleteData, PortalLoadingState, SourceAndDate } from "@/components/patient-portal/PortalStates";
import { PatientStatusBadge } from "@/components/patient-portal/PatientStatusBadge";
import { UrgentHelp } from "@/components/patient-portal/UrgentHelp";
import { getPortalSummary } from "@/lib/patient-portal/client";
import { usePortalData } from "@/lib/patient-portal/use-portal-data";

function dateTime(value?: string): string {
  if (!value) return "Not scheduled";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-US", { dateStyle: "medium", timeStyle: "short" }).format(date);
}

function SummaryCard({ title, icon: Icon, children, to, linkLabel }: { title: string; icon: typeof House; children: React.ReactNode; to: string; linkLabel: string }) {
  return <article className="flex min-h-[190px] flex-col rounded-lg border border-[var(--border)] bg-white p-5 shadow-[0_8px_22px_rgba(31,36,48,0.04)]"><h2 className="flex items-center gap-2 text-base font-semibold text-[color:var(--foreground)]"><Icon className="size-5 text-[color:var(--link)]" aria-hidden="true" />{title}</h2><div className="mt-4 flex-1 text-sm text-[color:var(--muted-foreground)]">{children}</div><Link to={to} className="mt-4 inline-flex min-h-11 items-center gap-2 border-t border-[var(--border)] pt-3 text-sm font-semibold text-[color:var(--brand)] hover:underline">{linkLabel}</Link></article>;
}

export function PortalHomePage() {
  const loader = useCallback(() => getPortalSummary(), []);
  const { data, loading, error, retry } = usePortalData(loader);
  if (loading) return <PortalLoadingState />;
  if (error || !data) return <PortalErrorState message={error ?? undefined} onRetry={retry} />;
  const dashboard = data.dashboard;
  const copdStatus = dashboard.copdStatus ?? { diagnosis: "COPD status not available", airflowLimitation: "Not available" };
  const respiratoryStatus = dashboard.respiratoryStatus ?? { latestSpO2: undefined, respiratoryRate: undefined, trend: "Not available" };
  const currentCare = dashboard.currentCare ?? { homeHealth: "Not available", pulmonaryRehab: "Not available", openTasks: 0 };
  const exacerbations = dashboard.exacerbations ?? { summary: "Not available", hospitalizations: 0 };
  return <div><PortalPageHeader title={`Welcome, ${data.patient.firstName}`} subtitle="Your COPD care, breathing support, and next steps in one place." icon={House} />{data.patient.synthetic && <p className="mb-5 rounded-lg border border-[var(--info-border)] bg-[var(--info-bg)] px-4 py-3 text-sm font-medium text-[color:var(--link)]">This portal contains synthetic demonstration data, not a real patient record.</p>}<PortalIncompleteData status={data.dataStatus} />
    <section aria-labelledby="status-heading" className="mb-7"><h2 id="status-heading" className="text-lg font-semibold">Current care status</h2><div className="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><SummaryCard title="COPD status" icon={Wind} to="/portal/symptoms-breathing" linkLabel="View breathing"><p className="font-semibold text-[color:var(--foreground)]">{copdStatus.diagnosis}</p><p className="mt-2">Airflow limitation: {copdStatus.airflowLimitation}</p></SummaryCard><SummaryCard title="Respiratory status" icon={Activity} to="/portal/symptoms-breathing" linkLabel="Review symptoms"><p>SpO2: {respiratoryStatus.latestSpO2 ?? "Not available"}</p><p>Respiratory rate: {respiratoryStatus.respiratoryRate ?? "Not available"}</p><p>Breathing trend: {respiratoryStatus.trend}</p></SummaryCard><SummaryCard title="Home health" icon={House} to="/portal/home-health" linkLabel="View home health"><p className="font-semibold text-[color:var(--foreground)]">{currentCare.homeHealth}</p><p className="mt-2">Visit details appear when available in your record.</p></SummaryCard><SummaryCard title="Pulmonary rehab" icon={Activity} to="/portal/pulmonary-rehab" linkLabel="View rehab"><p className="font-semibold text-[color:var(--foreground)]">{currentCare.pulmonaryRehab}</p><p className="mt-2">Your care team will share approved plans here.</p></SummaryCard></div></section>
    <section aria-labelledby="next-steps-heading" className="mb-7"><h2 id="next-steps-heading" className="text-lg font-semibold">Your next steps</h2>{dashboard.today.length === 0 ? <div className="mt-3"><PortalEmptyState title="No next steps are currently listed." detail="Ask your care team what to do next if you have questions." /></div> : <div className="mt-3 grid gap-3 lg:grid-cols-3">{dashboard.today.slice(0, 3).map(step => <article key={step.id} className="rounded-lg border border-[var(--border)] bg-white p-4"><PatientStatusBadge label={step.status} /><h3 className="mt-3 font-semibold">{step.title}</h3><p className="mt-1 text-sm leading-6 text-[color:var(--muted-foreground)]">{step.whyItMatters}</p>{step.patientAction && <p className="mt-3 text-sm font-medium">Your action: {step.patientAction}</p>}{step.dueDate && <p className="mt-1 text-xs text-[color:var(--muted-foreground)]">Due: {dateTime(step.dueDate)}</p>}</article>)}</div>}</section>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><SummaryCard title="Medications" icon={Pill} to="/portal/medications" linkLabel="View medications"><p className="text-2xl font-semibold text-[color:var(--foreground)]">{dashboard.medications?.activeCount ?? 0}</p><p>current medication{dashboard.medications?.activeCount === 1 ? "" : "s"} listed</p></SummaryCard><SummaryCard title="Recent exacerbations" icon={Activity} to="/portal/symptoms-breathing" linkLabel="Review breathing"><p className="font-semibold text-[color:var(--foreground)]">{exacerbations.summary}</p><p className="mt-2">Hospitalizations: {exacerbations.hospitalizations || "Not available"}</p></SummaryCard><SummaryCard title="Next appointment" icon={CalendarDays} to="/portal/appointments" linkLabel="View appointments">{dashboard.nextAppointment ? <><p className="font-semibold text-[color:var(--foreground)]">{dashboard.nextAppointment.title}</p><p className="mt-2">{dateTime(dashboard.nextAppointment.start)}</p></> : <p>No upcoming appointment is available.</p>}</SummaryCard><SummaryCard title="Care plan" icon={ClipboardList} to="/portal/care-plan" linkLabel="View care plan"><p>{dashboard.carePlan?.activeSteps ?? 0} active step{dashboard.carePlan?.activeSteps === 1 ? "" : "s"}</p><p className="mt-3 font-medium text-[color:var(--foreground)]">{dashboard.carePlan?.nextAction ?? "Not available"}</p></SummaryCard></div>
    <div className="mt-6 grid gap-4 lg:grid-cols-[1fr_0.7fr]"><UrgentHelp /><div className="rounded-lg border border-[var(--border)] bg-white p-4"><h2 className="flex items-center gap-2 text-sm font-semibold"><MessageCircle className="size-4 text-[color:var(--link)]" aria-hidden="true" />Care team updates</h2><p className="mt-2 text-sm text-[color:var(--muted-foreground)]">{dashboard.messages.latestSubject ?? "No new message is listed."}</p><Link to="/portal/messages" className="mt-3 inline-flex text-sm font-semibold text-[color:var(--brand)] hover:underline">Open messages</Link><SourceAndDate date={data.dataStatus.lastUpdatedAt} /></div></div>
  </div>;
}
