import { useState } from "react";
import { ShieldCheck, Type, UserRound } from "lucide-react";
import { useAuth } from "@/components/auth/AuthProvider";
import { PortalPageHeader } from "@/components/patient-portal/PortalPageHeader";
import { Button } from "@/components/ui/button";

export function PortalProfilePage() {
  const { user } = useAuth();
  const [largeText, setLargeText] = useState(document.documentElement.classList.contains("portal-text-large"));
  function setTextSize(large: boolean) { document.documentElement.classList.toggle("portal-text-large", large); setLargeText(large); }
  return <div><PortalPageHeader title="My Profile" subtitle="Review your portal identity, accessibility options, and privacy information." icon={UserRound} /><div className="grid gap-5 lg:grid-cols-2"><section className="rounded-lg border border-[#DCE6F0] bg-white p-5" aria-labelledby="profile-identity-heading"><h2 id="profile-identity-heading" className="text-lg font-semibold">Portal identity</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="font-semibold text-[#526172]">Name</dt><dd className="mt-1 text-[#1F2430]">{user?.displayName ?? "Patient portal user"}</dd></div><div><dt className="font-semibold text-[#526172]">Email</dt><dd className="mt-1 text-[#1F2430]">{user?.email ?? "Not available"}</dd></div><div><dt className="font-semibold text-[#526172]">Access type</dt><dd className="mt-1 text-[#1F2430]">Patient-only session</dd></div></dl><p className="mt-4 rounded-lg bg-[#EDF7FD] p-3 text-sm text-[#245D86]">This demonstration uses synthetic data and one-click role entry. It is not production authentication.</p></section><section id="accessibility" className="rounded-lg border border-[#DCE6F0] bg-white p-5" aria-labelledby="accessibility-heading"><h2 id="accessibility-heading" className="flex items-center gap-2 text-lg font-semibold"><Type className="size-5 text-[#3577A2]" aria-hidden="true" />Accessibility settings</h2><p className="mt-2 text-sm text-[#526172]">Choose the text size for this browser tab. Browser zoom and operating-system contrast settings are also supported.</p><div className="mt-4 inline-flex rounded-lg border border-[#CCDCE9] p-1" role="group" aria-label="Portal text size"><Button type="button" variant={!largeText ? "default" : "ghost"} onClick={() => setTextSize(false)}>Standard text</Button><Button type="button" variant={largeText ? "default" : "ghost"} onClick={() => setTextSize(true)}>Larger text</Button></div></section><section className="rounded-lg border border-[#DCE6F0] bg-white p-5 lg:col-span-2" aria-labelledby="privacy-heading"><h2 id="privacy-heading" className="flex items-center gap-2 text-lg font-semibold"><ShieldCheck className="size-5 text-[#2F7A4C]" aria-hidden="true" />Privacy and security</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6 text-[#526172]"><li>Your patient identity is resolved from the signed, HTTP-only session cookie.</li><li>The portal does not accept an editable patient ID for record access.</li><li>FHIR credentials and access tokens stay on the server and are not stored in browser local storage.</li><li>Logging out clears the application session and cached protected responses.</li><li>Do not use this synthetic demo for real patient information.</li></ul></section></div></div>;
}

