import { useCallback, useState } from "react";
import { Link } from "react-router-dom";
import { CalendarDays, CalendarPlus, CheckCircle2, Clock3, MapPin, MessageCircle, Send, Video } from "lucide-react";
import { PatientStatusBadge } from "@/components/patient-portal/PatientStatusBadge";
import { PortalPageHeader } from "@/components/patient-portal/PortalPageHeader";
import { PortalEmptyState, PortalErrorState, PortalIncompleteData, PortalLoadingState, SourceAndDate } from "@/components/patient-portal/PortalStates";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { getPortalAppointments, requestAppointmentChange } from "@/lib/patient-portal/client";
import { usePortalData } from "@/lib/patient-portal/use-portal-data";
import type { PatientAppointment } from "@/lib/patient-portal/types";

function dateTime(value?: string): string { if (!value) return "Scheduling in progress"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-US", { dateStyle: "full", timeStyle: "short", timeZoneName: "short" }).format(date); }

export function PortalAppointmentsPage() {
  const loader = useCallback(() => getPortalAppointments(), []);
  const { data, loading, error, retry } = usePortalData(loader);
  const [target, setTarget] = useState<PatientAppointment | null>(null);
  const [requestType, setRequestType] = useState("Request rescheduling");
  const [message, setMessage] = useState("");
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  if (loading) return <PortalLoadingState />;
  if (error || !data) return <PortalErrorState message={error ?? undefined} onRetry={retry} />;
  const upcoming = data.appointments.filter(item => !item.past);
  const past = data.appointments.filter(item => item.past);

  async function sendRequest() { if (!target) return; setSending(true); try { await requestAppointmentChange(target.id, requestType, message || undefined); setSent(true); setTarget(null); setMessage(""); } finally { setSending(false); } }
  async function confirm(appointment: PatientAppointment) { setSending(true); try { await requestAppointmentChange(appointment.id, "Appointment confirmation", "I am confirming that I plan to attend this appointment."); setSent(true); } finally { setSending(false); } }
  function addCalendar(appointment: PatientAppointment) { if (!appointment.start) return; const start = new Date(appointment.start).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, ""); const end = new Date(appointment.end ?? new Date(new Date(appointment.start).getTime() + 3_600_000)).toISOString().replace(/[-:]/g, "").replace(/\.\d{3}/, ""); const content = ["BEGIN:VCALENDAR", "VERSION:2.0", "BEGIN:VEVENT", `DTSTART:${start}`, `DTEND:${end}`, `SUMMARY:${appointment.title}`, `LOCATION:${appointment.location ?? appointment.organization ?? ""}`, "END:VEVENT", "END:VCALENDAR"].join("\r\n"); const url = URL.createObjectURL(new Blob([content], { type: "text/calendar" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "appointment.ics"; anchor.click(); URL.revokeObjectURL(url); }
  const AppointmentCard = ({ appointment, historical = false }: { appointment: PatientAppointment; historical?: boolean }) => <article className="rounded-lg border border-[#DCE6F0] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-[#1F2430]">{appointment.title}</h3><p className="mt-2 text-sm font-medium text-[#344253]">{dateTime(appointment.start)}</p></div><PatientStatusBadge label={appointment.statusLabel} /></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs font-semibold text-[#697586]">Provider</dt><dd className="mt-1">{appointment.provider}</dd></div><div><dt className="text-xs font-semibold text-[#697586]">Organization</dt><dd className="mt-1">{appointment.organization ?? "Not listed"}</dd></div>{appointment.location && <div className="sm:col-span-2"><dt className="flex items-center gap-1 text-xs font-semibold text-[#697586]"><MapPin className="size-3" aria-hidden="true" />Location</dt><dd className="mt-1">{appointment.location}</dd></div>}</dl>{appointment.preparation.length > 0 && <div className="mt-4 border-t border-[#E6ECF2] pt-3"><h4 className="text-sm font-semibold">Preparation supplied by the clinic</h4><ul className="mt-2 list-disc pl-5 text-sm text-[#526172]">{appointment.preparation.map(item => <li key={item}>{item}</li>)}</ul></div>}{!historical && <div className="mt-4 flex flex-wrap gap-2 border-t border-[#E6ECF2] pt-4"><Button size="sm" onClick={() => confirm(appointment)} disabled={sending}><CheckCircle2 aria-hidden="true" />Confirm attendance</Button>{appointment.start && <Button size="sm" variant="outline" onClick={() => addCalendar(appointment)}><CalendarPlus aria-hidden="true" />Add to calendar</Button>}{appointment.telehealthUrl && <Button asChild size="sm" variant="outline"><a href={appointment.telehealthUrl} target="_blank" rel="noreferrer"><Video aria-hidden="true" />Join telehealth</a></Button>}<Button size="sm" variant="outline" onClick={() => { setTarget(appointment); setRequestType("Request rescheduling"); }}><Clock3 aria-hidden="true" />Request change</Button><Button asChild size="sm" variant="link"><Link to="/portal/messages"><MessageCircle aria-hidden="true" />Ask a question</Link></Button></div>}</article>;
  return <div><PortalPageHeader title="Appointments" subtitle="Review upcoming visits, preparation details, and scheduling requests." icon={CalendarDays} /><PortalIncompleteData status={data.dataStatus} />{sent && <p role="status" aria-live="polite" className="mb-4 rounded-lg border border-[#BFDCC9] bg-[#EAF5EE] p-3 text-sm font-semibold text-[#2F6F47]">Your appointment request was recorded for scheduling review.</p>}{data.appointments.length === 0 ? <PortalEmptyState title="No appointments are available in your record yet." /> : <div className="space-y-7"><section><h2 className="text-lg font-semibold">Upcoming appointments</h2><div className="mt-3 grid gap-4 lg:grid-cols-2">{upcoming.length ? upcoming.map(item => <AppointmentCard key={item.id} appointment={item} />) : <PortalEmptyState title="No upcoming appointment is listed." detail="A follow-up may still be due even when an appointment has not been scheduled." />}</div></section>{past.length > 0 && <section><h2 className="text-lg font-semibold">Past appointments</h2><div className="mt-3 grid gap-4 lg:grid-cols-2">{past.map(item => <AppointmentCard key={item.id} appointment={item} historical />)}</div></section>}</div>}<div className="mt-5"><SourceAndDate date={data.dataStatus.lastUpdatedAt} /></div><Dialog open={Boolean(target)} onOpenChange={open => { if (!open) setTarget(null); }}><DialogContent><DialogHeader><DialogTitle>Request an appointment change</DialogTitle><DialogDescription>This sends a request to scheduling. It does not directly cancel or reschedule the appointment.</DialogDescription></DialogHeader><div className="space-y-3"><div><Label htmlFor="appointment-request-type">Request type</Label><select id="appointment-request-type" value={requestType} onChange={event => setRequestType(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[#BFCFDC] bg-white px-3"><option>Request rescheduling</option><option>Ask about location or telehealth</option><option>Ask about visit preparation</option></select></div><div><Label htmlFor="appointment-request-message">Message (optional)</Label><Textarea id="appointment-request-message" value={message} onChange={event => setMessage(event.target.value)} maxLength={1000} rows={4} className="mt-1" /></div></div><DialogFooter><Button variant="outline" onClick={() => setTarget(null)}>Cancel</Button><Button onClick={sendRequest} disabled={sending}><Send aria-hidden="true" />{sending ? "Sending..." : "Send request"}</Button></DialogFooter></DialogContent></Dialog></div>;
}

