import { Link } from "react-router-dom";
import { CircleHelp, Clock3, MessageCircle, PhoneCall, ShieldAlert } from "lucide-react";
import { PortalPageHeader } from "@/components/patient-portal/PortalPageHeader";
import { Button } from "@/components/ui/button";

export function PortalHelpPage() {
  return <div><PortalPageHeader title="Help" subtitle="Choose the right way to get help with your portal or care questions." icon={CircleHelp} /><section className="grid gap-4 md:grid-cols-2" aria-label="Help levels"><article className="rounded-lg border border-[var(--border)] bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><MessageCircle className="size-5 text-[color:var(--link)]" aria-hidden="true" />Routine question</h2><p className="mt-2 text-sm leading-6 text-[color:var(--muted-foreground)]">Use secure Messages for a non-urgent question about appointments, medicines, nutrition, results, or your care plan.</p><Button asChild variant="outline" className="mt-4 min-h-11"><Link to="/portal/messages">Open Messages</Link></Button></article><article className="rounded-lg border border-[var(--border)] bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><Clock3 className="size-5 text-[color:var(--warning-text)]" aria-hidden="true" />Contact care team soon</h2><p className="mt-2 text-sm leading-6 text-[color:var(--muted-foreground)]">Use the contact method your clinic gave you when a concern should not wait for routine messaging. This demo does not provide a clinic phone number.</p></article><article className="rounded-lg border border-[var(--yellow)] bg-[var(--warning-bg)] p-5"><h2 className="flex items-center gap-2 font-semibold text-[color:var(--warning-text)]"><ShieldAlert className="size-5" aria-hidden="true" />Urgent clinical concern</h2><p className="mt-2 text-sm leading-6 text-[color:var(--warning-text)]">Follow the urgent-contact instructions supplied by your organization. This portal does not improvise medical triage thresholds.</p></article><article className="rounded-lg border border-[#F2CBD1] bg-[#FFF4F5] p-5"><h2 className="flex items-center gap-2 font-semibold text-[#812D3B]"><PhoneCall className="size-5" aria-hidden="true" />Emergency</h2><p className="mt-2 text-sm leading-6 text-[#6B3A43]">Contact your local emergency services now. Do not send an emergency message through this portal.</p></article></section><section className="mt-6 rounded-lg border border-[var(--border)] bg-white p-5"><h2 className="text-lg font-semibold">Portal support</h2><p className="mt-2 text-sm leading-6 text-[color:var(--muted-foreground)]">If a page will not load, use its Try again button. If your record looks incomplete, send a secure message to your care team. Sign out when using a shared device.</p></section></div>;
}

