import { useCallback } from "react";
import { CheckCircle2, Circle, ClipboardList, MessageCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { PatientStatusBadge } from "@/components/patient-portal/PatientStatusBadge";
import { PortalEmptyState, PortalErrorState, PortalIncompleteData, PortalLoadingState, SourceAndDate } from "@/components/patient-portal/PortalStates";
import { PortalPageHeader } from "@/components/patient-portal/PortalPageHeader";
import { getPortalCarePlan } from "@/lib/patient-portal/client";
import { usePortalData } from "@/lib/patient-portal/use-portal-data";

function dateOnly(value?: string) { if (!value) return "Not listed"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(date); }
export function PortalCarePlanPage() {
  const loader = useCallback(() => getPortalCarePlan(), []); const { data, loading, error, retry } = usePortalData(loader);
  if (loading) return <PortalLoadingState />; if (error || !data) return <PortalErrorState message={error ?? undefined} onRetry={retry} />;
  return <div><PortalPageHeader title="My Care Plan" subtitle="See what is planned, what is in progress, and what you need to do next." icon={ClipboardList} /><PortalIncompleteData status={data.dataStatus} />{data.pathways.length === 0 ? <PortalEmptyState title="No next steps are listed yet." detail="Your care team will add your plan here when it is ready to share." /> : <div className="space-y-4">{data.pathways.map(pathway => <article key={pathway.id} className="rounded-lg border border-[var(--border)] bg-white p-5 shadow-[0_4px_16px_rgba(31,36,48,0.04)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{pathway.title}</h2><p className="mt-1 text-sm leading-6 text-[color:var(--muted-foreground)]">{pathway.purpose}</p></div><PatientStatusBadge label={pathway.statusLabel} /></div><dl className="mt-5 grid gap-4 border-y border-[var(--border)] py-4 sm:grid-cols-3"><div><dt className="text-xs font-semibold text-[color:var(--muted-foreground)]">Next step</dt><dd className="mt-1 text-sm font-medium">{pathway.nextStep}</dd></div><div><dt className="text-xs font-semibold text-[color:var(--muted-foreground)]">Who can help</dt><dd className="mt-1 text-sm font-medium">{pathway.responsibleParty}</dd></div><div><dt className="text-xs font-semibold text-[color:var(--muted-foreground)]">Due date</dt><dd className="mt-1 text-sm font-medium">{dateOnly(pathway.dueDate)}</dd></div></dl>{pathway.patientAction && <p className="mt-4 rounded-md bg-[var(--info-bg)] p-3 text-sm text-[color:var(--link)]"><strong>Your action:</strong> {pathway.patientAction}</p>}<h3 className="mt-5 text-sm font-semibold">Progress</h3><ul className="mt-2 grid gap-2 sm:grid-cols-2">{pathway.milestones.map(item => <li key={item.label} className="flex items-center gap-2 text-sm text-[color:var(--muted-foreground)]">{item.completed ? <CheckCircle2 className="size-4 text-[color:var(--success)]" aria-hidden="true" /> : <Circle className="size-4" aria-hidden="true" />}{item.label}</li>)}</ul><Link to="/portal/messages" className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-[color:var(--brand)] hover:underline"><MessageCircle className="size-4" aria-hidden="true" />Ask your care team a question</Link></article>)}</div>}<div className="mt-5"><SourceAndDate date={data.dataStatus.lastUpdatedAt} /></div></div>;
}
