import { useCallback, useState } from "react";
import { Link } from "react-router-dom";
import { AlertTriangle, MessageCircle, Pill, RefreshCw, Send } from "lucide-react";
import { PatientStatusBadge } from "@/components/patient-portal/PatientStatusBadge";
import { PortalPageHeader } from "@/components/patient-portal/PortalPageHeader";
import { PortalEmptyState, PortalErrorState, PortalIncompleteData, PortalLoadingState, SourceAndDate } from "@/components/patient-portal/PortalStates";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { getPortalMedications, requestMedicationRefill } from "@/lib/patient-portal/client";
import { usePortalData } from "@/lib/patient-portal/use-portal-data";
import type { PatientMedication } from "@/lib/patient-portal/types";

export function PortalMedicationsPage() {
  const loader = useCallback(() => getPortalMedications(), []);
  const { data, loading, error, retry } = usePortalData(loader);
  const [target, setTarget] = useState<PatientMedication | null>(null);
  const [message, setMessage] = useState("");
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  if (loading) return <PortalLoadingState />;
  if (error || !data) return <PortalErrorState message={error ?? undefined} onRetry={retry} />;
  async function requestRefill() { if (!target) return; setSending(true); try { await requestMedicationRefill(target.id, message || undefined); setSent(true); setTarget(null); setMessage(""); } finally { setSending(false); } }
  const active = data.medications.filter(item => item.status === "active");
  const inactive = data.medications.filter(item => item.status !== "active");
  const MedicationCard = ({ medication }: { medication: PatientMedication }) => <article className="rounded-lg border border-[#DCE6F0] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-[#1F2430]">{medication.name}</h3><p className="mt-1 text-sm text-[#526172]">{[medication.dose, medication.route, medication.frequency].filter(Boolean).join(" · ") || "Dose instructions are not available"}</p></div><PatientStatusBadge label={medication.status} /></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs font-semibold text-[#697586]">What it is for</dt><dd className="mt-1">{medication.reason ?? "Not listed"}</dd></div><div><dt className="text-xs font-semibold text-[#697586]">Prescriber</dt><dd className="mt-1">{medication.prescriber ?? "Not listed"}</dd></div><div><dt className="text-xs font-semibold text-[#697586]">Start date</dt><dd className="mt-1">{medication.startDate ? new Date(medication.startDate).toLocaleDateString() : "Not listed"}</dd></div><div><dt className="text-xs font-semibold text-[#697586]">Refill status</dt><dd className="mt-1">{medication.refillStatus ?? "No refill update listed"}</dd></div></dl>{medication.monitoring.length > 0 && <div className="mt-4 border-t border-[#E6ECF2] pt-3"><h4 className="text-sm font-semibold">Monitoring listed by your care team</h4><ul className="mt-2 space-y-2">{medication.monitoring.map(item => <li key={item.label} className="flex flex-wrap items-center justify-between gap-2 text-sm text-[#526172]"><span>{item.label}</span><PatientStatusBadge label={item.status} /></li>)}</ul></div>}<div className="mt-4 flex flex-wrap gap-2 border-t border-[#E6ECF2] pt-4">{medication.status === "active" && <Button size="sm" onClick={() => setTarget(medication)}><RefreshCw aria-hidden="true" />Request refill</Button>}<Button asChild size="sm" variant="outline"><Link to="/portal/messages"><MessageCircle aria-hidden="true" />Ask a medication question</Link></Button><Button asChild size="sm" variant="link"><Link to="/portal/messages">Report a problem</Link></Button></div></article>;
  return <div><PortalPageHeader title="Medications" subtitle="Review medicines listed in your record and send requests to your care team." icon={Pill} /><PortalIncompleteData status={data.dataStatus} /><aside className="mb-5 rounded-lg border border-[#F0D49C] bg-[#FFF9EC] p-4"><p className="flex items-start gap-2 text-sm font-semibold text-[#6F4A13]"><AlertTriangle className="mt-0.5 size-5 shrink-0" aria-hidden="true" />Do not change or stop a medication without speaking with your care team.</p></aside>{sent && <p role="status" className="mb-4 rounded-lg border border-[#BFDCC9] bg-[#EAF5EE] p-3 text-sm font-semibold text-[#2F6F47]">Your refill request was recorded for medication-team review.</p>}{data.medications.length === 0 ? <PortalEmptyState title="No medications are available in this section yet." detail="This does not mean you should stop medicines you are taking. Contact your care team if your list looks incomplete." /> : <div className="space-y-7"><section><h2 className="text-lg font-semibold">Current medications</h2><div className="mt-3 grid gap-4 lg:grid-cols-2">{active.length ? active.map(item => <MedicationCard key={item.id} medication={item} />) : <PortalEmptyState title="No current medications are listed." />}</div></section>{inactive.length > 0 && <section><h2 className="text-lg font-semibold">Stopped or inactive medications</h2><div className="mt-3 grid gap-4 lg:grid-cols-2">{inactive.map(item => <MedicationCard key={item.id} medication={item} />)}</div></section>}</div>}<div className="mt-5"><SourceAndDate date={data.dataStatus.lastUpdatedAt} /></div><Dialog open={Boolean(target)} onOpenChange={open => { if (!open) setTarget(null); }}><DialogContent><DialogHeader><DialogTitle>Request refill review</DialogTitle><DialogDescription>This creates a patient request for your medication team. It does not create or sign a prescription.</DialogDescription></DialogHeader><p className="font-semibold">{target?.name}</p><div><Label htmlFor="refill-message">Message (optional)</Label><Textarea id="refill-message" className="mt-1" rows={4} maxLength={1000} value={message} onChange={event => setMessage(event.target.value)} /></div><DialogFooter><Button variant="outline" onClick={() => setTarget(null)}>Cancel</Button><Button onClick={requestRefill} disabled={sending}><Send aria-hidden="true" />{sending ? "Sending..." : "Send refill request"}</Button></DialogFooter></DialogContent></Dialog></div>;
}

