import { useCallback, useState } from "react";
import { MessageCircle, Send } from "lucide-react";
import { PortalPageHeader } from "@/components/patient-portal/PortalPageHeader";
import { PortalEmptyState, PortalErrorState, PortalIncompleteData, PortalLoadingState, SourceAndDate } from "@/components/patient-portal/PortalStates";
import { getPortalMessages, sendPortalMessage } from "@/lib/patient-portal/client";
import { usePortalData } from "@/lib/patient-portal/use-portal-data";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const RECIPIENTS = ["Pulmonology team", "Home health nurse", "Care coordinator", "Care team", "Medication questions", "Appointment questions"];
export function PortalMessagesPage() {
  const loader = useCallback(() => getPortalMessages(), []); const { data, loading, error, retry } = usePortalData(loader); const [category, setCategory] = useState(RECIPIENTS[0]!); const [subject, setSubject] = useState(""); const [message, setMessage] = useState(""); const [sent, setSent] = useState(false); const [sending, setSending] = useState(false);
  if (loading) return <PortalLoadingState />; if (error || !data) return <PortalErrorState message={error ?? undefined} onRetry={retry} />;
  async function send() { if (!subject.trim() || !message.trim()) return; setSending(true); try { await sendPortalMessage(category, subject, message); setSent(true); setSubject(""); setMessage(""); } finally { setSending(false); } }
  return <div><PortalPageHeader title="Messages" subtitle="Send a question to your care team. Messages are read and answered by your care team." icon={MessageCircle} /><PortalIncompleteData status={data.dataStatus} />{sent && <p role="status" className="mb-5 rounded-md border border-[var(--mint)] bg-[var(--success-bg)] p-3 text-sm font-semibold text-[color:var(--success)]">Your message was sent for care-team review.</p>}<div className="grid gap-6 lg:grid-cols-[1.1fr_0.9fr]"><section className="rounded-lg border border-[var(--border)] bg-white p-5"><h2 className="text-base font-semibold">Start a message</h2><div className="mt-4 space-y-4"><div><Label htmlFor="message-recipient">Send to</Label><select id="message-recipient" value={category} onChange={event => setCategory(event.target.value)} className="mt-1 min-h-11 w-full rounded-md border border-[var(--input)] bg-white px-3 text-sm">{RECIPIENTS.map(item => <option key={item}>{item}</option>)}</select></div><div><Label htmlFor="message-subject">Subject</Label><input id="message-subject" value={subject} onChange={event => setSubject(event.target.value)} className="mt-1 h-11 w-full rounded-md border border-[var(--input)] px-3 text-sm" /></div><div><Label htmlFor="message-body">Message</Label><Textarea id="message-body" value={message} onChange={event => setMessage(event.target.value)} rows={6} className="mt-1" /></div><Button type="button" className="min-h-11" disabled={sending || !subject.trim() || !message.trim()} onClick={send}><Send aria-hidden="true" />{sending ? "Sending..." : "Send message"}</Button></div></section><section><h2 className="mb-3 text-base font-semibold">Recent messages</h2>{data.messages.length === 0 ? <PortalEmptyState title="No messages yet." detail="Your care team messages will appear here." /> : <div className="space-y-3">{data.messages.map(item => <article key={item.id} className="rounded-lg border border-[var(--border)] bg-white p-4"><p className="text-xs font-semibold uppercase tracking-wide text-[color:var(--muted-foreground)]">{item.sender}</p><h3 className="mt-1 font-semibold">{item.subject}</h3><p className="mt-2 text-sm leading-6 text-[color:var(--muted-foreground)]">{item.preview}</p></article>)}</div>}</section></div><div className="mt-5"><SourceAndDate date={data.dataStatus.lastUpdatedAt} /></div></div>;
}
