import { Link } from "react-router-dom";
import { AppShell } from "@/components/layout/AppShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { getClinicianWorklist } from "@/lib/worklist-client";
import { getPatientQuestionnaireResponses } from "@/lib/fhir";
import { useEffect, useState } from "react";
import type { ClinicianWorklistResponse } from "@/lib/worklist-types";

export function NurseAssessmentsPage() {
  const [data, setData] = useState<ClinicianWorklistResponse | null>(null);
  useEffect(() => { getClinicianWorklist().then(setData).catch(() => setData(null)); }, []);
  const patients = data?.allPatients.filter(view => view.hasCopd) ?? [];
  const [responses, setResponses] = useState<Record<string, fhir4.QuestionnaireResponse | null>>({});
  useEffect(() => { if (patients.length) Promise.all(patients.filter(view => view.patient.id).map(async view => [view.patient.id!, (await getPatientQuestionnaireResponses(view.patient.id!)).filter(response => response.questionnaire?.includes("copd-home-health-subset")).sort((a, b) => (b.authored ?? "").localeCompare(a.authored ?? ""))[0] ?? null] as const)).then(entries => setResponses(Object.fromEntries(entries))); }, [data]);
  return <AppShell title="Assessments" subtitle="COPD home-health assessments."><Card className="gap-0 overflow-hidden py-0 shadow-none"><CardContent className="p-0"><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead><tr className="border-b border-[var(--border)] bg-[var(--background)] text-xs font-semibold text-[color:var(--brand)]"><th className="px-4 py-3">Patient</th><th className="px-4 py-3">Assessment type</th><th className="px-4 py-3">Visit</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Progress</th><th className="px-4 py-3">Last updated</th><th className="px-4 py-3">Action</th></tr></thead><tbody>{patients.flatMap(view => { const response = responses[view.patient.id ?? ""]; const completed = response?.status === "completed"; return [<tr key={`${view.patient.id}-oasis`} className="border-b border-[var(--border)]"><td className="px-4 py-4 font-semibold text-[color:var(--brand)]">{view.name}</td><td className="px-4 py-4">OASIS-E2 Demo Subset · Start of Care</td><td className="px-4 py-4">Home-health visit</td><td className="px-4 py-4"><Badge variant={completed ? "success" : "neutral"}>{completed ? "Completed" : "Not started"}</Badge></td><td className="px-4 py-4">{completed ? "100%" : "—"}</td><td className="px-4 py-4">{completed && response?.authored ? new Date(response.authored).toLocaleDateString() : "—"}</td><td className="px-4 py-4"><Button asChild size="sm" variant="outline"><Link to={`/nurse/assessments/${view.patient.id}/oasis`}>{completed ? "Review" : "Start"}</Link></Button></td></tr>, <tr key={`${view.patient.id}-copd`} className="border-b border-[var(--border)]"><td className="px-4 py-4 font-semibold text-[color:var(--brand)]">{view.name}</td><td className="px-4 py-4">Waypoint COPD Home Health Assessment</td><td className="px-4 py-4">Home-health visit</td><td className="px-4 py-4"><Badge variant={completed ? "success" : view.openTaskCount > 0 ? "warning" : "neutral"}>{completed ? "Completed" : view.openTaskCount > 0 ? "In progress" : "Not started"}</Badge></td><td className="px-4 py-4">{completed ? "100%" : view.openTaskCount > 0 ? "In progress" : "—"}</td><td className="px-4 py-4">{response?.authored ? new Date(response.authored).toLocaleDateString() : "—"}</td><td className="px-4 py-4"><Button asChild size="sm"><Link to={`/nurse/visits/${view.patient.id}`}>{completed ? "Review" : view.openTaskCount > 0 ? "Continue" : "Start"}</Link></Button></td></tr>]; })}</tbody></table></div></CardContent></Card></AppShell>;
}
